# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgapp < Formula
  desc "A powerful CLI for the Create Go App project. Create a new production-ready project with backend, frontend and deploy automation by running one CLI command!"
  homepage "https://create-go.app/"
  version "v2.1.0"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/create-go-app/cli/releases/download/v2.1.0/cgapp_v2.1.0_macOS_x86_64.tar.gz"
    sha256 "b82e2de1fedce337af9e2ac821e942309c8cef5e20eb65bbd7e49212722d60ac"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/create-go-app/cli/releases/download/v2.1.0/cgapp_v2.1.0_macOS_arm64.tar.gz"
    sha256 "4949e5e24df9a3131f55129e18f34b5da532c2f54ec4a22c4c9614b2187c1261"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/create-go-app/cli/releases/download/v2.1.0/cgapp_v2.1.0_Linux_x86_64.tar.gz"
    sha256 "1e4d80765c8ed83aa3e1cbc0377bbacbdd8a6dc1327f09bc279e6db2274712ed"
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "cgapp"
  end

  def caveats; <<~EOS
    Create a new project via interactive console UI into current folder by using `cgapp create` command.
  EOS
  end
end
