# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgapp < Formula
  desc "A powerful CLI for the Create Go App project. Create a new production-ready project with backend, frontend and deploy automation by running one CLI command!"
  homepage "https://create-go.app/"
  version "v3.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/create-go-app/cli/releases/download/v3.5.0/cgapp_v3.5.0_macOS_arm64.tar.gz"
      sha256 "66ff5a0dccfad4dc0313c6f34f26fdc5310997820c3eeb422be8be724867a2e8"

      def install
        bin.install "cgapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v3.5.0/cgapp_v3.5.0_macOS_x86_64.tar.gz"
      sha256 "dbc4c8edd48b1c238d334600815bcfd956d845401b04ffb9b2dc4221f9a84961"

      def install
        bin.install "cgapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v3.5.0/cgapp_v3.5.0_Linux_x86_64.tar.gz"
      sha256 "9613ae990a88f798d4ac358c7a595d4f6efd122ca9cbc3090885195813a38af3"

      def install
        bin.install "cgapp"
      end
    end
  end

  depends_on "npm"
  depends_on "git"
  depends_on "go"

  def caveats; <<~EOS
    Create a new project via interactive console UI into current folder by using `cgapp create` command. A helpful documentation and next steps with your project is here https://create-go.app/
  EOS
  end
end
