# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgapp < Formula
  desc "Create a new production-ready project with backend (Golang), frontend (JavaScript, TypeScript) and deploy automation (Ansible, Docker) by running one CLI command.
Focus on writing code and thinking of business-logic! The CLI will take care of the rest.
"
  homepage "https://github.com/create-go-app/cli"
  version "4.1.0"
  license "Apache 2.0"

  depends_on "git"
  depends_on "npm"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/create-go-app/cli/releases/download/v4.1.0/cgapp_4.1.0_darwin_arm64.tar.gz"
      sha256 "6459f419def6e401c2e6ac9ad97eaea1527701caf9443add322d054644d19a05"

      def install
        bin.install "cgapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v4.1.0/cgapp_4.1.0_darwin_amd64.tar.gz"
      sha256 "83a09c9386867c8a87fafccd567d4bdefd287fa5d248ffac9ae6471e6ae40aa0"

      def install
        bin.install "cgapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-go-app/cli/releases/download/v4.1.0/cgapp_4.1.0_linux_arm64.tar.gz"
      sha256 "df3cf86ac6c74d7072aff6118136accb06a5547bdf377ede51ab20aa94b41bb2"

      def install
        bin.install "cgapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v4.1.0/cgapp_4.1.0_linux_amd64.tar.gz"
      sha256 "a391f92ec914c0634810de54347e4e49dd183c00749769e3c098a7b0d7ce1c0b"

      def install
        bin.install "cgapp"
      end
    end
  end

  def caveats
    <<~EOS
      After install (or update) cgapp, let's create a new project via interactive console UI in current folder:

      $ cgapp create

      Next, open the generated Ansible inventory file (called hosts.ini) and fill in the variables according to your server configuration.

      And you're ready to automatically deploy this project:

      $ cgapp deploy

      That's all you need to know to start! 🎉
    EOS
  end
end
