# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgapp < Formula
  desc "Create a new production-ready project with backend (Golang), frontend (JavaScript, TypeScript) and deploy automation (Ansible, Docker) by running one CLI command.
Focus on writing code and thinking of business-logic! The CLI will take care of the rest.
"
  homepage "https://github.com/create-go-app/cli"
  version "4.0.1"
  license "Apache 2.0"

  depends_on "git"
  depends_on "npm"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.1/cgapp_4.0.1_darwin_arm64.tar.gz"
      sha256 "fe965da42fe261096caf2b4900047818d893438ec9e059f1e403bcb313dbdadd"

      def install
        bin.install "cgapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.1/cgapp_4.0.1_darwin_amd64.tar.gz"
      sha256 "94d72492c108c3963d9c0eb9b1a329561e0b17e7b1ff08084b7d06bd8828edfb"

      def install
        bin.install "cgapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.1/cgapp_4.0.1_linux_arm64.tar.gz"
      sha256 "20d7ac57361e8ef807315851b7703ab6ede3a8a29d4c80be2d4ef5258e8cabd6"

      def install
        bin.install "cgapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.1/cgapp_4.0.1_linux_amd64.tar.gz"
      sha256 "37c151e47092889e6fb6c01693461a9a8bda31f236b04f49b284c67a356b76ee"

      def install
        bin.install "cgapp"
      end
    end
  end

  def caveats
    <<~EOS
      After install cgapp, let's create a new project via interactive console UI (or CUI for short) in current folder:

      $ cgapp create

      Next, open the generated Ansible inventory file (called hosts.ini) and fill in the variables according to your server configuration.

      And you're ready to automatically deploy this project:

      $ cgapp deploy

      That's all you need to know to start! 🎉
    EOS
  end
end
