# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgapp < Formula
  desc "Create a new production-ready project with backend (Golang), frontend (JavaScript, TypeScript) and deploy automation (Ansible, Docker) by running one CLI command.
Focus on writing code and thinking of business-logic! The CLI will take care of the rest.
"
  homepage "https://github.com/create-go-app/cli"
  version "4.0.0"
  license "Apache 2.0"

  depends_on "git"
  depends_on "npm"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.0/cgapp_4.0.0_darwin_arm64.tar.gz"
      sha256 "9ac6742ff848081c025f424c3795c98fec1b5692958e6c281e16101759f098c3"

      def install
        bin.install "cgapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.0/cgapp_4.0.0_darwin_amd64.tar.gz"
      sha256 "1dceac86a71524f5fd3840b12c1af16cdf63dfa1ab9e228bb70248a58fc37b7c"

      def install
        bin.install "cgapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.0/cgapp_4.0.0_linux_arm64.tar.gz"
      sha256 "30100177415edaa8ab87011d8410462fd82c8316029eda92811b180643cd42d2"

      def install
        bin.install "cgapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/create-go-app/cli/releases/download/v4.0.0/cgapp_4.0.0_linux_amd64.tar.gz"
      sha256 "46e518ca70a8fb7412fad9b2ff1c62f6bb426f83d6e0ed5b7c1a0bc3011c03be"

      def install
        bin.install "cgapp"
      end
    end
  end

  def caveats
    <<~EOS
      After install cgapp, let's create a new project via interactive console UI (or CUI for short) in current folder:

      $ cgapp create

      Next, open the generated Ansible inventory file (called hosts.ini) and fill in the variables according to your server configuration.

      And you're ready to automatically deploy this project:

      $ cgapp deploy

      That's all you need to know to start! 🎉
    EOS
  end
end
